apiVersion: v1
kind: Service
metadata:
  name: {{ include "sms-app.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sms-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "sms-app.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
