apiVersion: v1
kind: Service
metadata:
  name: {{ include "sms-app.fullname" . }}-model-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sms-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: model-service
spec:
  type: {{ .Values.modelService.service.type }}
  selector:
    {{- include "sms-app.modelService.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.modelService.service.port }}
      targetPort: http
      protocol: TCP
