apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-stack.fullname" . }}-model-service
  labels:
    app.kubernetes.io/component: model-service
    {{- include "app-stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.modelService.service.type }}
  selector:
    app.kubernetes.io/component: model-service
    {{- include "app-stack.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.modelService.service.port }}
      targetPort: {{ .Values.modelService.containerPort }}
