{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ include "app-stack.fullname" . }}
  labels:
    {{- include "app-stack.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceMonitorSelector:
    matchLabels:
      {{- with .Values.monitoring.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-stack.fullname" . }}-prometheus
  labels:
    {{- include "app-stack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9090
      targetPort: 9090
  selector:
    prometheus: {{ include "app-stack.fullname" . }}
{{- end }}
