apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sms-app.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sms-app.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  FEATURE_FLAG_EXAMPLE: {{ .Values.config.featureFlagExample | quote }}
