---
- name: Base system setup for all Kubernetes nodes
  hosts: all
  become: yes

  vars:
    ssh_keys_dir: "{{ playbook_dir }}/files/ssh_keys"

  tasks:
    - name: Show which host we are configuring
      debug:
        msg: "Configuring base system on {{ inventory_hostname }}"
